-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_r_TVALID : IN STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    in_r_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    in_r_TREADY : OUT STD_LOGIC;
    out_r_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of fir is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_fir,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu48dr-ffvg1517-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.560437,HLS_SYN_LAT=106,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=506,HLS_SYN_LUT=3492,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_FFFFCCCC : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111100110011001100";
    constant ap_const_lv32_2666 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000010011001100110";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_7FFFE666 : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111110011001100110";
    constant ap_const_lv29_666 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000011001100110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_FFFFD999 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111101100110011001";
    constant ap_const_lv31_1999 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000001100110011001";
    constant ap_const_lv30_CCC : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000110011001100";
    constant ap_const_lv30_3FFFF333 : STD_LOGIC_VECTOR (29 downto 0) := "111111111111111111001100110011";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal regslice_both_out_r_U_apdone_blk : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal icmp_ln12_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal in_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal reg_11_reg_722 : STD_LOGIC_VECTOR (16 downto 0);
    signal reg_17_fu_231_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal reg_17_reg_728 : STD_LOGIC_VECTOR (16 downto 0);
    signal reg_14_reg_747 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal trunc_ln_reg_753 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln25_1_reg_758 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_336_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln25_3_reg_778 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_3_reg_783 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln25_4_reg_788 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_446_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln25_6_reg_813 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_6_reg_818 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_456_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln25_7_reg_823 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_466_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln25_8_reg_828 : STD_LOGIC_VECTOR (29 downto 0);
    signal reg_81_fu_116 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal n10_fu_120 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal n_fu_255_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_n10_load : STD_LOGIC_VECTOR (6 downto 0);
    signal reg_fu_124 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal reg_1_fu_128 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal reg_2_fu_132 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal reg_3_fu_136 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal reg_4_fu_140 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal reg_5_fu_144 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal ap_sig_allocacmp_reg_11 : STD_LOGIC_VECTOR (16 downto 0);
    signal reg_6_fu_148 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal ap_sig_allocacmp_reg_10 : STD_LOGIC_VECTOR (16 downto 0);
    signal reg_7_fu_152 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal ap_sig_allocacmp_reg_9 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal sext_ln25_fu_235_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_239_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln25_2_fu_245_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_249_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln_fu_296_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln25_1_fu_303_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_fu_307_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_326_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln25_7_fu_332_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_336_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln25_9_fu_342_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_346_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_375_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln25_3_fu_382_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_4_fu_386_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_1_fu_389_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_2_fu_395_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_326_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal shl_ln25_2_fu_405_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_6_fu_413_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_2_fu_417_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_436_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln25_13_fu_442_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_446_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln25_15_fu_452_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_456_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln25_17_fu_462_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_466_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln25_3_fu_486_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_8_fu_493_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_3_fu_496_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_4_fu_502_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln25_4_fu_512_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_10_fu_520_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_4_fu_523_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_5_fu_529_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_436_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln25_5_fu_539_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_12_fu_547_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_5_fu_551_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal shl_ln25_6_fu_567_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_14_fu_574_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_6_fu_577_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_7_fu_583_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln25_7_fu_593_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_16_fu_601_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_7_fu_604_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_8_fu_610_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln25_8_fu_620_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln25_18_fu_628_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_8_fu_631_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_9_fu_637_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_239_ce : STD_LOGIC;
    signal grp_fu_249_ce : STD_LOGIC;
    signal grp_fu_326_ce : STD_LOGIC;
    signal grp_fu_336_ce : STD_LOGIC;
    signal grp_fu_346_ce : STD_LOGIC;
    signal grp_fu_436_ce : STD_LOGIC;
    signal grp_fu_446_ce : STD_LOGIC;
    signal grp_fu_456_ce : STD_LOGIC;
    signal grp_fu_466_ce : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal regslice_both_in_r_U_apdone_blk : STD_LOGIC;
    signal in_r_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal in_r_TVALID_int_regslice : STD_LOGIC;
    signal in_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_r_U_ack_in : STD_LOGIC;
    signal out_r_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal out_r_TVALID_int_regslice : STD_LOGIC;
    signal out_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_r_U_vld_out : STD_LOGIC;
    signal ap_condition_261 : BOOLEAN;
    signal ap_condition_609 : BOOLEAN;
    signal ap_condition_608 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component fir_mul_17s_15s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fir_mul_17s_15ns_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fir_mul_17s_14s_31_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component fir_mul_17s_12ns_29_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component fir_mul_17s_14ns_31_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component fir_mul_17s_13ns_30_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component fir_mul_17s_13s_30_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component fir_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component fir_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;


    component fir_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component fir_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    mul_17s_15s_32_2_1_U1 : component fir_mul_17s_15s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_fu_235_p0,
        din1 => grp_fu_239_p1,
        ce => grp_fu_239_ce,
        dout => grp_fu_239_p2);

    mul_17s_15ns_32_2_1_U2 : component fir_mul_17s_15ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_2_fu_245_p0,
        din1 => grp_fu_249_p1,
        ce => grp_fu_249_ce,
        dout => grp_fu_249_p2);

    mul_17s_14s_31_2_1_U3 : component fir_mul_17s_14s_31_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 14,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => reg_11_reg_722,
        din1 => grp_fu_326_p1,
        ce => grp_fu_326_ce,
        dout => grp_fu_326_p2);

    mul_17s_12ns_29_2_1_U4 : component fir_mul_17s_12ns_29_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 12,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_7_fu_332_p0,
        din1 => grp_fu_336_p1,
        ce => grp_fu_336_ce,
        dout => grp_fu_336_p2);

    mul_17s_15ns_32_2_1_U5 : component fir_mul_17s_15ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_9_fu_342_p0,
        din1 => grp_fu_346_p1,
        ce => grp_fu_346_ce,
        dout => grp_fu_346_p2);

    mul_17s_15s_32_2_1_U6 : component fir_mul_17s_15s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => reg_14_reg_747,
        din1 => grp_fu_436_p1,
        ce => grp_fu_436_ce,
        dout => grp_fu_436_p2);

    mul_17s_14ns_31_2_1_U7 : component fir_mul_17s_14ns_31_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 14,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_13_fu_442_p0,
        din1 => grp_fu_446_p1,
        ce => grp_fu_446_ce,
        dout => grp_fu_446_p2);

    mul_17s_13ns_30_2_1_U8 : component fir_mul_17s_13ns_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_15_fu_452_p0,
        din1 => grp_fu_456_p1,
        ce => grp_fu_456_ce,
        dout => grp_fu_456_p2);

    mul_17s_13s_30_2_1_U9 : component fir_mul_17s_13s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => sext_ln25_17_fu_462_p0,
        din1 => grp_fu_466_p1,
        ce => grp_fu_466_ce,
        dout => grp_fu_466_p2);

    flow_control_loop_delay_pipe_U : component fir_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);

    regslice_both_in_r_U : component fir_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TDATA,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_U_ack_in,
        data_out => in_r_TDATA_int_regslice,
        vld_out => in_r_TVALID_int_regslice,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_U_apdone_blk);

    regslice_both_out_r_U : component fir_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_r_TDATA_int_regslice,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => out_r_TREADY_int_regslice,
        data_out => out_r_TDATA,
        vld_out => regslice_both_out_r_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
            else
                if ((ap_start_int = ap_const_logic_1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;

    n10_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_261)) then
                n10_fu_120 <= n_fu_255_p2;
            end if;
        end if;
    end process;

    reg_1_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if ((ap_const_boolean_1 = ap_condition_609)) then 
                    reg_1_fu_128 <= ap_const_lv17_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reg_1_fu_128 <= reg_14_reg_747;
                end if;
            end if; 
        end if;
    end process;

    reg_2_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_const_boolean_1 = ap_condition_608)) then 
                    reg_2_fu_132 <= ap_const_lv17_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reg_2_fu_132 <= reg_3_fu_136;
                end if;
            end if; 
        end if;
    end process;

    reg_3_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_const_boolean_1 = ap_condition_608)) then 
                    reg_3_fu_136 <= ap_const_lv17_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reg_3_fu_136 <= reg_4_fu_140;
                end if;
            end if; 
        end if;
    end process;

    reg_4_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_const_boolean_1 = ap_condition_608)) then 
                    reg_4_fu_140 <= ap_const_lv17_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    reg_4_fu_140 <= reg_11_reg_722;
                end if;
            end if; 
        end if;
    end process;

    reg_5_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_261)) then
                reg_5_fu_144 <= ap_sig_allocacmp_reg_10;
            end if;
        end if;
    end process;

    reg_6_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_261)) then
                reg_6_fu_148 <= ap_sig_allocacmp_reg_9;
            end if;
        end if;
    end process;

    reg_7_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_261)) then
                reg_7_fu_152 <= reg_17_fu_231_p1;
            end if;
        end if;
    end process;

    reg_81_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if ((ap_const_boolean_1 = ap_condition_609)) then 
                    reg_81_fu_116 <= ap_const_lv17_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reg_81_fu_116 <= reg_fu_124;
                end if;
            end if; 
        end if;
    end process;

    reg_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if ((ap_const_boolean_1 = ap_condition_609)) then 
                    reg_fu_124 <= ap_const_lv17_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    reg_fu_124 <= reg_1_fu_128;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
                ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                mul_ln25_1_reg_758 <= grp_fu_249_p2;
                reg_11_reg_722 <= ap_sig_allocacmp_reg_11;
                reg_17_reg_728 <= reg_17_fu_231_p1;
                trunc_ln_reg_753 <= add_ln25_fu_307_p2(31 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                mul_ln25_3_reg_778 <= grp_fu_336_p2;
                mul_ln25_4_reg_788 <= grp_fu_346_p2;
                mul_ln25_6_reg_813 <= grp_fu_446_p2;
                mul_ln25_7_reg_823 <= grp_fu_456_p2;
                mul_ln25_8_reg_828 <= grp_fu_466_p2;
                tmp_3_reg_783 <= add_ln25_2_fu_417_p2(32 downto 14);
                tmp_6_reg_818 <= add_ln25_5_fu_551_p2(32 downto 14);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                reg_14_reg_747 <= reg_2_fu_132;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln25_1_fu_389_p2 <= std_logic_vector(signed(sext_ln25_3_fu_382_p1) + signed(sext_ln25_4_fu_386_p1));
    add_ln25_2_fu_417_p2 <= std_logic_vector(unsigned(shl_ln25_2_fu_405_p3) + unsigned(sext_ln25_6_fu_413_p1));
    add_ln25_3_fu_496_p2 <= std_logic_vector(unsigned(shl_ln25_3_fu_486_p3) + unsigned(sext_ln25_8_fu_493_p1));
    add_ln25_4_fu_523_p2 <= std_logic_vector(unsigned(shl_ln25_4_fu_512_p3) + unsigned(sext_ln25_10_fu_520_p1));
    add_ln25_5_fu_551_p2 <= std_logic_vector(unsigned(shl_ln25_5_fu_539_p3) + unsigned(sext_ln25_12_fu_547_p1));
    add_ln25_6_fu_577_p2 <= std_logic_vector(unsigned(shl_ln25_6_fu_567_p3) + unsigned(sext_ln25_14_fu_574_p1));
    add_ln25_7_fu_604_p2 <= std_logic_vector(unsigned(shl_ln25_7_fu_593_p3) + unsigned(sext_ln25_16_fu_601_p1));
    add_ln25_8_fu_631_p2 <= std_logic_vector(unsigned(shl_ln25_8_fu_620_p3) + unsigned(sext_ln25_18_fu_628_p1));
    add_ln25_fu_307_p2 <= std_logic_vector(signed(sext_ln25_1_fu_303_p1) + signed(grp_fu_239_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_pp0_stage0_subdone_grp1_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, ap_start_int, in_r_TVALID_int_regslice, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_out_r_U_apdone_blk = ap_const_logic_1) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((in_r_TVALID_int_regslice = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_done_reg = ap_const_logic_1)))));
    end process;


    ap_block_pp0_stage0_11001_grp0_assign_proc : process(ap_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_pp0_stage0_subdone_grp1_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_block_pp0_stage0_subdone_grp1_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, ap_start_int, in_r_TVALID_int_regslice, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_out_r_U_apdone_blk = ap_const_logic_1) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((in_r_TVALID_int_regslice = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_done_reg = ap_const_logic_1)))));
    end process;


    ap_block_pp0_stage0_subdone_grp0_assign_proc : process(ap_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone_grp0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_done_reg, ap_block_pp0_stage0_subdone_grp1_done_reg, regslice_both_out_r_U_apdone_blk, ap_loop_exit_ready_pp0_iter5_reg, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (regslice_both_out_r_U_apdone_blk = ap_const_logic_1)) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((out_r_TREADY_int_regslice = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_condition_261_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_261 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_608_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_loop_init, ap_start_int)
    begin
                ap_condition_608 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_609_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, ap_loop_init, ap_start_int)
    begin
                ap_condition_609 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln12_fu_261_p2, ap_start_int)
    begin
        if (((icmp_ln12_fu_261_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n10_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, n10_fu_120, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n10_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_n10_load <= n10_fu_120;
        end if; 
    end process;


    ap_sig_allocacmp_reg_10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, reg_6_fu_148, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_reg_10 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_reg_10 <= reg_6_fu_148;
        end if; 
    end process;


    ap_sig_allocacmp_reg_11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, reg_5_fu_144, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_reg_11 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_reg_11 <= reg_5_fu_144;
        end if; 
    end process;


    ap_sig_allocacmp_reg_9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, reg_7_fu_152, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_reg_9 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_reg_9 <= reg_7_fu_152;
        end if; 
    end process;


    grp_fu_239_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_239_ce <= ap_const_logic_1;
        else 
            grp_fu_239_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_239_p1 <= ap_const_lv32_FFFFCCCC(15 - 1 downto 0);

    grp_fu_249_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_249_ce <= ap_const_logic_1;
        else 
            grp_fu_249_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_249_p1 <= ap_const_lv32_2666(15 - 1 downto 0);

    grp_fu_326_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_326_ce <= ap_const_logic_1;
        else 
            grp_fu_326_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_326_p1 <= ap_const_lv31_7FFFE666(14 - 1 downto 0);

    grp_fu_336_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_336_ce <= ap_const_logic_1;
        else 
            grp_fu_336_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_336_p1 <= ap_const_lv29_666(12 - 1 downto 0);

    grp_fu_346_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_346_ce <= ap_const_logic_1;
        else 
            grp_fu_346_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_346_p1 <= ap_const_lv32_2666(15 - 1 downto 0);

    grp_fu_436_ce_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_436_ce <= ap_const_logic_1;
        else 
            grp_fu_436_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_436_p1 <= ap_const_lv32_FFFFD999(15 - 1 downto 0);

    grp_fu_446_ce_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_446_ce <= ap_const_logic_1;
        else 
            grp_fu_446_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_446_p1 <= ap_const_lv31_1999(14 - 1 downto 0);

    grp_fu_456_ce_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_456_ce <= ap_const_logic_1;
        else 
            grp_fu_456_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_456_p1 <= ap_const_lv30_CCC(13 - 1 downto 0);

    grp_fu_466_ce_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_466_ce <= ap_const_logic_1;
        else 
            grp_fu_466_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_466_p1 <= ap_const_lv30_3FFFF333(13 - 1 downto 0);
    icmp_ln12_fu_261_p2 <= "1" when (ap_sig_allocacmp_n10_load = ap_const_lv7_63) else "0";

    in_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0, ap_start_int, in_r_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_done_reg = ap_const_logic_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_r_TDATA_blk_n <= in_r_TVALID_int_regslice;
        else 
            in_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_r_TREADY <= regslice_both_in_r_U_ack_in;

    in_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    n_fu_255_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n10_load) + unsigned(ap_const_lv7_1));

    out_r_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1, out_r_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            out_r_TDATA_blk_n <= out_r_TREADY_int_regslice;
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_637_p4),24));
    out_r_TVALID <= regslice_both_out_r_U_vld_out;

    out_r_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    reg_17_fu_231_p1 <= in_r_TDATA_int_regslice(17 - 1 downto 0);
        sext_ln25_10_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln25_4_reg_788),33));

        sext_ln25_12_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_436_p2),33));

    sext_ln25_13_fu_442_p0 <= reg_1_fu_128;
        sext_ln25_14_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln25_6_reg_813),33));

    sext_ln25_15_fu_452_p0 <= reg_fu_124;
        sext_ln25_16_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln25_7_reg_823),33));

    sext_ln25_17_fu_462_p0 <= reg_81_fu_116;
        sext_ln25_18_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln25_8_reg_828),33));

        sext_ln25_1_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_296_p3),32));

    sext_ln25_2_fu_245_p0 <= ap_sig_allocacmp_reg_10;
        sext_ln25_3_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_375_p3),33));

        sext_ln25_4_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln25_1_reg_758),33));

        sext_ln25_6_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_326_p2),33));

    sext_ln25_7_fu_332_p0 <= reg_4_fu_140;
        sext_ln25_8_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln25_3_reg_778),33));

    sext_ln25_9_fu_342_p0 <= reg_3_fu_136;
    sext_ln25_fu_235_p0 <= ap_sig_allocacmp_reg_9;
    shl_ln25_2_fu_405_p3 <= (tmp_2_fu_395_p4 & ap_const_lv14_0);
    shl_ln25_3_fu_486_p3 <= (tmp_3_reg_783 & ap_const_lv14_0);
    shl_ln25_4_fu_512_p3 <= (tmp_4_fu_502_p4 & ap_const_lv14_0);
    shl_ln25_5_fu_539_p3 <= (tmp_5_fu_529_p4 & ap_const_lv14_0);
    shl_ln25_6_fu_567_p3 <= (tmp_6_reg_818 & ap_const_lv14_0);
    shl_ln25_7_fu_593_p3 <= (tmp_7_fu_583_p4 & ap_const_lv14_0);
    shl_ln25_8_fu_620_p3 <= (tmp_8_fu_610_p4 & ap_const_lv14_0);
    shl_ln_fu_296_p3 <= (reg_17_reg_728 & ap_const_lv14_0);
    tmp_1_fu_375_p3 <= (trunc_ln_reg_753 & ap_const_lv14_0);
    tmp_2_fu_395_p4 <= add_ln25_1_fu_389_p2(32 downto 14);
    tmp_4_fu_502_p4 <= add_ln25_3_fu_496_p2(32 downto 14);
    tmp_5_fu_529_p4 <= add_ln25_4_fu_523_p2(32 downto 14);
    tmp_7_fu_583_p4 <= add_ln25_6_fu_577_p2(32 downto 14);
    tmp_8_fu_610_p4 <= add_ln25_7_fu_604_p2(32 downto 14);
    tmp_9_fu_637_p4 <= add_ln25_8_fu_631_p2(32 downto 14);
end behav;
